-- 在目标SQL Server库中执行

ALTER TABLE User_User ADD SrcId BIGINT NOT NULL DEFAULT(0)
ALTER TABLE Finance_Account ADD SrcId BIGINT NOT NULL DEFAULT(0)
ALTER TABLE dbo.User_UserTypeIndex ADD SrcId BIGINT NOT NULL DEFAULT(0)
ALTER TABLE dbo.User_PlacementRelation ADD SrcId BIGINT NOT NULL DEFAULT(0)

ALTER TABLE dbo.FenRun_LevelTouchValue ADD SrcId BIGINT NOT NULL DEFAULT(0)